/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Obsidian MCP Manager Plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObsidianMCPPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// types.ts
var DEFAULT_SETTINGS = {
  containerName: "obsidian-mcp-server",
  autoStart: true
};

// docker-manager.ts
var import_child_process = require("child_process");
var DockerManager = class {
  constructor(settings) {
    this.statusCache = null;
    this.statusCacheTime = 0;
    this.CACHE_TTL = 5e3;
    // 5秒缓存
    this.MAX_RETRIES = 3;
    this.containerName = settings.containerName;
  }
  /**
   * 启动容器（带重试机制）
   */
  async start() {
    console.log(`Starting container: ${this.containerName}`);
    for (let attempt = 1; attempt <= this.MAX_RETRIES; attempt++) {
      try {
        await this.execDocker(["start", this.containerName]);
        this.statusCache = "running";
        this.statusCacheTime = Date.now();
        console.log(`Container ${this.containerName} started successfully`);
        return;
      } catch (error) {
        console.warn(`Start attempt ${attempt}/${this.MAX_RETRIES} failed:`, error);
        if (attempt === this.MAX_RETRIES) {
          throw new Error(`Failed to start container after ${this.MAX_RETRIES} attempts: ${error}`);
        }
        const delay = Math.pow(2, attempt) * 1e3;
        console.log(`Retrying in ${delay}ms...`);
        await this.sleep(delay);
      }
    }
  }
  /**
   * 停止容器
   */
  async stop() {
    try {
      console.log(`Stopping container: ${this.containerName}`);
      await this.execDocker(["stop", this.containerName]);
      this.statusCache = "stopped";
      this.statusCacheTime = Date.now();
      console.log(`Container ${this.containerName} stopped successfully`);
    } catch (error) {
      console.error("Failed to stop container:", error);
    }
  }
  /**
   * 重启容器
   */
  async restart() {
    console.log(`Restarting container: ${this.containerName}`);
    await this.stop();
    await this.sleep(1e3);
    await this.start();
  }
  /**
   * 获取容器状态（带缓存）
   */
  async getStatus() {
    if (this.statusCache && Date.now() - this.statusCacheTime < this.CACHE_TTL) {
      return this.statusCache;
    }
    try {
      const output = await this.execDocker([
        "ps",
        "-a",
        "--filter",
        `name=^/${this.containerName}$`,
        "--format",
        "{{.Status}}"
      ]);
      let status;
      if (output.includes("Up")) {
        status = "running";
      } else if (output.includes("Exited")) {
        status = "stopped";
      } else if (output.trim() === "") {
        status = "unknown";
      } else {
        status = "unknown";
      }
      this.statusCache = status;
      this.statusCacheTime = Date.now();
      return status;
    } catch (error) {
      console.error("Failed to get container status:", error);
      return "error";
    }
  }
  /**
   * 获取容器日志
   */
  async getLogs(lines = 100) {
    try {
      const output = await this.execDocker([
        "logs",
        "--tail",
        lines.toString(),
        this.containerName
      ]);
      return output || "(\u5BB9\u5668\u65E5\u5FD7\u4E3A\u7A7A)";
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : String(error);
      return `\u65E0\u6CD5\u83B7\u53D6\u65E5\u5FD7: ${errorMsg}`;
    }
  }
  /**
   * 清除状态缓存（用于强制刷新）
   */
  clearCache() {
    this.statusCache = null;
    this.statusCacheTime = 0;
  }
  /**
   * 执行 Docker 命令
   */
  async execDocker(args) {
    return new Promise((resolve, reject) => {
      const dockerProcess = (0, import_child_process.spawn)("docker", args, { shell: true });
      let stdout = "";
      let stderr = "";
      dockerProcess.stdout.on("data", (data) => {
        stdout += data.toString();
      });
      dockerProcess.stderr.on("data", (data) => {
        stderr += data.toString();
      });
      dockerProcess.on("error", (error) => {
        reject(new Error(`Failed to spawn docker process: ${error.message}`));
      });
      dockerProcess.on("close", (code) => {
        if (code === 0) {
          resolve(stdout.trim());
        } else {
          const errorMsg = stderr.trim() || `Docker command failed with exit code ${code}`;
          reject(new Error(errorMsg));
        }
      });
    });
  }
  /**
   * 延迟辅助函数
   */
  sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
};

// status-bar.ts
var import_obsidian = require("obsidian");
var StatusBarManager = class {
  constructor(statusBarEl, dockerManager, app) {
    this.updateInterval = null;
    this.statusIcons = {
      running: "\u{1F7E2}",
      starting: "\u{1F7E1}",
      stopped: "\u{1F534}",
      error: "\u26A0\uFE0F",
      unknown: "\u2753"
    };
    this.statusBarEl = statusBarEl;
    this.dockerManager = dockerManager;
    this.app = app;
    this.setStatus("starting");
    this.statusBarEl.addEventListener("click", () => {
      this.refreshStatus();
    });
    this.statusBarEl.addEventListener("contextmenu", (e) => {
      e.preventDefault();
      this.showContextMenu(e);
    });
    this.updateInterval = setInterval(() => this.updateStatus(), 3e4);
  }
  /**
   * 设置状态栏显示
   */
  setStatus(status) {
    const icon = this.statusIcons[status] || this.statusIcons.unknown;
    this.statusBarEl.setText(`${icon} MCP`);
    this.statusBarEl.title = `MCP Server \u72B6\u6001: ${this.getStatusText(status)}`;
  }
  /**
   * 异步更新状态（静默）
   */
  async updateStatus() {
    try {
      const status = await this.dockerManager.getStatus();
      this.setStatus(status);
    } catch (error) {
      console.error("Failed to update status:", error);
    }
  }
  /**
   * 刷新状态（带反馈）
   */
  async refreshStatus() {
    try {
      this.dockerManager.clearCache();
      const status = await this.dockerManager.getStatus();
      this.setStatus(status);
      new import_obsidian.Notice(`MCP Server \u72B6\u6001: ${this.getStatusText(status)}`);
    } catch (error) {
      new import_obsidian.Notice("\u65E0\u6CD5\u83B7\u53D6\u5BB9\u5668\u72B6\u6001");
      console.error("Failed to refresh status:", error);
    }
  }
  /**
   * 显示右键菜单
   */
  showContextMenu(event) {
    const menu = new import_obsidian.Menu();
    menu.addItem((item) => {
      item.setTitle("\u5237\u65B0\u72B6\u6001").setIcon("refresh-cw").onClick(() => this.refreshStatus());
    });
    menu.addSeparator();
    menu.addItem((item) => {
      item.setTitle("\u91CD\u542F MCP Server").setIcon("rotate-cw").onClick(async () => {
        try {
          new import_obsidian.Notice("\u6B63\u5728\u91CD\u542F MCP Server...");
          this.setStatus("starting");
          await this.dockerManager.restart();
          this.setStatus("running");
          new import_obsidian.Notice("MCP Server \u5DF2\u91CD\u542F");
        } catch (error) {
          this.setStatus("error");
          new import_obsidian.Notice("MCP Server \u91CD\u542F\u5931\u8D25");
          console.error("Failed to restart:", error);
        }
      });
    });
    menu.addItem((item) => {
      item.setTitle("\u505C\u6B62 MCP Server").setIcon("square").onClick(async () => {
        try {
          await this.dockerManager.stop();
          this.setStatus("stopped");
          new import_obsidian.Notice("MCP Server \u5DF2\u505C\u6B62");
        } catch (error) {
          new import_obsidian.Notice("\u505C\u6B62 MCP Server \u5931\u8D25");
          console.error("Failed to stop:", error);
        }
      });
    });
    menu.addSeparator();
    menu.addItem((item) => {
      item.setTitle("\u67E5\u770B\u65E5\u5FD7").setIcon("file-text").onClick(() => {
        this.app.commands.executeCommandById("obsidian-mcp:view-logs");
      });
    });
    menu.addSeparator();
    menu.addItem((item) => {
      item.setTitle("\u6253\u5F00\u8BBE\u7F6E").setIcon("settings").onClick(() => {
        this.app.setting.open();
        this.app.setting.openTabById("obsidian-mcp");
      });
    });
    menu.showAtMouseEvent(event);
  }
  /**
   * 获取状态文本
   */
  getStatusText(status) {
    const texts = {
      running: "\u8FD0\u884C\u4E2D",
      starting: "\u542F\u52A8\u4E2D",
      stopped: "\u5DF2\u505C\u6B62",
      error: "\u9519\u8BEF",
      unknown: "\u672A\u77E5"
    };
    return texts[status] || "\u672A\u77E5";
  }
  /**
   * 清理资源
   */
  destroy() {
    if (this.updateInterval) {
      clearInterval(this.updateInterval);
      this.updateInterval = null;
    }
  }
};

// log-modal.ts
var import_obsidian2 = require("obsidian");
var LogModal = class extends import_obsidian2.Modal {
  constructor(app, dockerManager) {
    super(app);
    this.autoRefresh = false;
    this.refreshInterval = null;
    this.dockerManager = dockerManager;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    this.modalEl.style.width = "80%";
    this.modalEl.style.maxWidth = "1000px";
    contentEl.createEl("h2", { text: "MCP Server \u65E5\u5FD7" });
    const toolbar = contentEl.createDiv({ cls: "log-toolbar" });
    toolbar.style.marginBottom = "10px";
    toolbar.style.display = "flex";
    toolbar.style.gap = "10px";
    toolbar.style.alignItems = "center";
    const refreshBtn = toolbar.createEl("button", { text: "\u{1F504} \u5237\u65B0" });
    refreshBtn.style.padding = "5px 10px";
    refreshBtn.style.cursor = "pointer";
    refreshBtn.onclick = () => this.refreshLogs();
    const autoRefreshLabel = toolbar.createEl("label");
    autoRefreshLabel.style.display = "flex";
    autoRefreshLabel.style.alignItems = "center";
    autoRefreshLabel.style.gap = "5px";
    const autoRefreshCheckbox = autoRefreshLabel.createEl("input", {
      type: "checkbox"
    });
    autoRefreshCheckbox.checked = this.autoRefresh;
    autoRefreshCheckbox.onchange = () => {
      this.autoRefresh = autoRefreshCheckbox.checked;
      this.toggleAutoRefresh();
    };
    autoRefreshLabel.createEl("span", { text: "\u81EA\u52A8\u5237\u65B0\uFF08\u6BCF5\u79D2\uFF09" });
    const clearBtn = toolbar.createEl("button", { text: "\u6E05\u7A7A\u663E\u793A" });
    clearBtn.style.padding = "5px 10px";
    clearBtn.style.cursor = "pointer";
    clearBtn.onclick = () => {
      this.logContent.empty();
      this.logContent.setText("(\u663E\u793A\u5DF2\u6E05\u7A7A\uFF0C\u70B9\u51FB\u5237\u65B0\u6309\u94AE\u91CD\u65B0\u52A0\u8F7D\u65E5\u5FD7)");
    };
    const copyBtn = toolbar.createEl("button", { text: "\u{1F4CB} \u590D\u5236\u65E5\u5FD7" });
    copyBtn.style.padding = "5px 10px";
    copyBtn.style.cursor = "pointer";
    copyBtn.onclick = () => this.copyLogs();
    const linesLabel = toolbar.createEl("label");
    linesLabel.style.display = "flex";
    linesLabel.style.alignItems = "center";
    linesLabel.style.gap = "5px";
    linesLabel.style.marginLeft = "auto";
    linesLabel.createEl("span", { text: "\u663E\u793A\u884C\u6570:" });
    const linesSelect = linesLabel.createEl("select");
    linesSelect.style.padding = "5px";
    [50, 100, 200, 500, 1e3].forEach((num) => {
      const option = linesSelect.createEl("option", {
        text: num.toString(),
        value: num.toString()
      });
      if (num === 100)
        option.selected = true;
    });
    linesSelect.onchange = () => this.refreshLogs(parseInt(linesSelect.value));
    this.logContent = contentEl.createEl("pre", {
      cls: "mcp-server-logs"
    });
    this.logContent.style.maxHeight = "500px";
    this.logContent.style.overflowY = "auto";
    this.logContent.style.overflowX = "auto";
    this.logContent.style.background = "#1e1e1e";
    this.logContent.style.color = "#d4d4d4";
    this.logContent.style.padding = "15px";
    this.logContent.style.fontFamily = "monospace";
    this.logContent.style.fontSize = "12px";
    this.logContent.style.lineHeight = "1.5";
    this.logContent.style.borderRadius = "5px";
    this.logContent.style.whiteSpace = "pre-wrap";
    this.logContent.style.wordBreak = "break-all";
    this.refreshLogs();
  }
  /**
   * 刷新日志
   */
  async refreshLogs(lines = 100) {
    try {
      this.logContent.setText("\u6B63\u5728\u52A0\u8F7D\u65E5\u5FD7...");
      const logs = await this.dockerManager.getLogs(lines);
      if (!logs || logs.trim() === "") {
        this.logContent.setText("(\u5BB9\u5668\u65E5\u5FD7\u4E3A\u7A7A)");
      } else {
        this.logContent.setText(logs);
        requestAnimationFrame(() => {
          this.logContent.scrollTop = this.logContent.scrollHeight;
        });
      }
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : String(error);
      this.logContent.setText(`\u274C \u65E0\u6CD5\u52A0\u8F7D\u65E5\u5FD7: ${errorMsg}`);
      console.error("Failed to load logs:", error);
    }
  }
  /**
   * 切换自动刷新
   */
  toggleAutoRefresh() {
    if (this.autoRefresh) {
      this.refreshInterval = setInterval(() => {
        this.refreshLogs();
      }, 5e3);
    } else {
      if (this.refreshInterval) {
        clearInterval(this.refreshInterval);
        this.refreshInterval = null;
      }
    }
  }
  /**
   * 复制日志到剪贴板
   */
  async copyLogs() {
    try {
      const logs = this.logContent.textContent || "";
      await navigator.clipboard.writeText(logs);
      const originalText = this.logContent.textContent;
      this.logContent.setText("\u2705 \u65E5\u5FD7\u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F\uFF01\n\n" + logs);
      setTimeout(() => {
        if (originalText) {
          this.logContent.setText(originalText);
        }
      }, 1e3);
    } catch (error) {
      console.error("Failed to copy logs:", error);
      this.logContent.setText("\u274C \u590D\u5236\u5931\u8D25\n\n" + this.logContent.textContent);
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
    if (this.refreshInterval) {
      clearInterval(this.refreshInterval);
      this.refreshInterval = null;
    }
  }
};

// settings.ts
var import_obsidian3 = require("obsidian");
var SettingsTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Obsidian MCP Server \u8BBE\u7F6E" });
    new import_obsidian3.Setting(containerEl).setName("MCP Server \u5BB9\u5668\u540D\u79F0").setDesc("Obsidian MCP Server \u7684 Docker \u5BB9\u5668\u540D\u79F0").addText((text) => text.setPlaceholder("obsidian-mcp-server").setValue(this.plugin.settings.containerName).onChange(async (value) => {
      this.plugin.settings.containerName = value;
      await this.plugin.saveSettings();
      new import_obsidian3.Notice("\u5BB9\u5668\u540D\u79F0\u5DF2\u66F4\u65B0\uFF0C\u4E0B\u6B21\u542F\u52A8\u65F6\u751F\u6548");
    }));
    new import_obsidian3.Setting(containerEl).setName("\u81EA\u52A8\u542F\u52A8 MCP Server").setDesc("Obsidian \u542F\u52A8\u65F6\u81EA\u52A8\u542F\u52A8 MCP Server \u5BB9\u5668").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoStart).onChange(async (value) => {
      this.plugin.settings.autoStart = value;
      await this.plugin.saveSettings();
      new import_obsidian3.Notice(`\u81EA\u52A8\u542F\u52A8\u5DF2${value ? "\u542F\u7528" : "\u7981\u7528"}`);
    }));
    containerEl.createEl("h3", { text: "\u5BB9\u5668\u72B6\u6001" });
    const statusContainer = containerEl.createDiv();
    statusContainer.style.marginBottom = "20px";
    this.showContainerStatus(statusContainer);
    new import_obsidian3.Setting(containerEl).setName("\u6D4B\u8BD5 Docker \u8FDE\u63A5").setDesc("\u6D4B\u8BD5 Docker \u662F\u5426\u53EF\u7528\u4EE5\u53CA\u5BB9\u5668\u662F\u5426\u5B58\u5728").addButton((button) => button.setButtonText("\u6D4B\u8BD5\u8FDE\u63A5").onClick(async () => {
      await this.testDockerConnection();
    }));
    new import_obsidian3.Setting(containerEl).setName("\u5237\u65B0\u5BB9\u5668\u72B6\u6001").setDesc("\u5F3A\u5236\u5237\u65B0\u5BB9\u5668\u72B6\u6001\u663E\u793A").addButton((button) => button.setButtonText("\u5237\u65B0").onClick(async () => {
      statusContainer.empty();
      await this.showContainerStatus(statusContainer);
      new import_obsidian3.Notice("\u72B6\u6001\u5DF2\u5237\u65B0");
    }));
    containerEl.createEl("h3", { text: "\u5E2E\u52A9" });
    const helpDiv = containerEl.createDiv();
    helpDiv.style.padding = "10px";
    helpDiv.style.backgroundColor = "#f0f0f0";
    helpDiv.style.borderRadius = "5px";
    helpDiv.style.marginTop = "10px";
    helpDiv.createEl("p", {
      text: "\u6B64\u63D2\u4EF6\u7BA1\u7406 Obsidian MCP Server \u7684 Docker \u5BB9\u5668\u751F\u547D\u5468\u671F\u3002"
    });
    helpDiv.createEl("p", {
      text: "\u529F\u80FD\uFF1A"
    });
    const featureList = helpDiv.createEl("ul");
    featureList.createEl("li", { text: "\u81EA\u52A8\u542F\u52A8/\u505C\u6B62\u5BB9\u5668\uFF08\u968F Obsidian \u542F\u52A8/\u5173\u95ED\uFF09" });
    featureList.createEl("li", { text: "\u72B6\u6001\u680F\u663E\u793A\u5BB9\u5668\u72B6\u6001" });
    featureList.createEl("li", { text: "\u53F3\u952E\u83DC\u5355\u5FEB\u901F\u64CD\u4F5C\uFF08\u91CD\u542F\u3001\u505C\u6B62\u3001\u67E5\u770B\u65E5\u5FD7\uFF09" });
    featureList.createEl("li", { text: "\u547D\u4EE4\u9762\u677F\u96C6\u6210" });
    helpDiv.createEl("p", {
      text: "\u63D0\u793A\uFF1A\u53F3\u952E\u70B9\u51FB\u72B6\u6001\u680F\u56FE\u6807\u53EF\u5FEB\u901F\u91CD\u542F\u6216\u505C\u6B62\u5BB9\u5668\u3002"
    });
  }
  /**
   * 显示容器状态
   */
  async showContainerStatus(containerEl) {
    try {
      this.plugin.dockerManager.clearCache();
      const status = await this.plugin.dockerManager.getStatus();
      const statusDiv = containerEl.createEl("div", {
        cls: "mcp-status-info"
      });
      statusDiv.style.padding = "10px";
      statusDiv.style.marginTop = "10px";
      statusDiv.style.borderRadius = "5px";
      let bgColor;
      let textColor;
      let statusText;
      switch (status) {
        case "running":
          bgColor = "#d4edda";
          textColor = "#155724";
          statusText = "\u2705 \u8FD0\u884C\u4E2D";
          break;
        case "stopped":
          bgColor = "#f8d7da";
          textColor = "#721c24";
          statusText = "\u{1F534} \u5DF2\u505C\u6B62";
          break;
        case "starting":
          bgColor = "#fff3cd";
          textColor = "#856404";
          statusText = "\u{1F7E1} \u542F\u52A8\u4E2D";
          break;
        case "error":
          bgColor = "#f8d7da";
          textColor = "#721c24";
          statusText = "\u26A0\uFE0F \u9519\u8BEF";
          break;
        default:
          bgColor = "#e2e3e5";
          textColor = "#383d41";
          statusText = "\u2753 \u672A\u77E5";
      }
      statusDiv.style.backgroundColor = bgColor;
      statusDiv.style.color = textColor;
      statusDiv.style.fontWeight = "bold";
      statusDiv.createEl("div", {
        text: `\u5F53\u524D\u5BB9\u5668\u72B6\u6001: ${statusText}`
      });
      statusDiv.createEl("div", {
        text: `\u5BB9\u5668\u540D\u79F0: ${this.plugin.settings.containerName}`,
        attr: {
          style: "margin-top: 5px; font-size: 0.9em; font-weight: normal;"
        }
      });
    } catch (error) {
      const errorDiv = containerEl.createEl("div", {
        text: `\u65E0\u6CD5\u83B7\u53D6\u5BB9\u5668\u72B6\u6001: ${error.message}`
      });
      errorDiv.style.padding = "10px";
      errorDiv.style.backgroundColor = "#f8d7da";
      errorDiv.style.color = "#721c24";
      errorDiv.style.borderRadius = "5px";
      errorDiv.style.marginTop = "10px";
    }
  }
  /**
   * 测试 Docker 连接
   */
  async testDockerConnection() {
    try {
      const status = await this.plugin.dockerManager.getStatus();
      let message;
      switch (status) {
        case "running":
          message = "\u2705 Docker \u8FDE\u63A5\u6210\u529F\uFF01\u5BB9\u5668\u6B63\u5728\u8FD0\u884C\u3002";
          break;
        case "stopped":
          message = "\u2705 Docker \u8FDE\u63A5\u6210\u529F\uFF01\u5BB9\u5668\u5DF2\u505C\u6B62\u3002";
          break;
        case "unknown":
          message = "\u26A0\uFE0F Docker \u8FDE\u63A5\u6210\u529F\uFF0C\u4F46\u5BB9\u5668\u4E0D\u5B58\u5728\u6216\u540D\u79F0\u4E0D\u6B63\u786E\u3002";
          break;
        default:
          message = `\u26A0\uFE0F Docker \u8FDE\u63A5\u6210\u529F\uFF0C\u5BB9\u5668\u72B6\u6001: ${status}`;
      }
      new import_obsidian3.Notice(message, 5e3);
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : String(error);
      new import_obsidian3.Notice(`\u274C Docker \u8FDE\u63A5\u5931\u8D25: ${errorMsg}`, 5e3);
      console.error("Docker connection test failed:", error);
    }
  }
};

// main.ts
var ObsidianMCPPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    console.log("Loading Obsidian MCP Manager plugin");
    await this.loadSettings();
    this.dockerManager = new DockerManager(this.settings);
    this.statusBarItem = new StatusBarManager(
      this.addStatusBarItem(),
      this.dockerManager,
      this.app
    );
    this.addCommand({
      id: "view-logs",
      name: "View MCP Server Logs",
      callback: () => this.openLogModal()
    });
    this.addCommand({
      id: "restart-container",
      name: "Restart MCP Server",
      callback: () => this.restartContainer()
    });
    this.addCommand({
      id: "stop-container",
      name: "Stop MCP Server",
      callback: () => this.stopContainer()
    });
    if (this.settings.autoStart) {
      this.startContainerAsync();
    }
    this.addSettingTab(new SettingsTab(this.app, this));
    console.log("Obsidian MCP Manager plugin loaded");
  }
  async onunload() {
    console.log("Unloading Obsidian MCP Manager plugin");
    if (this.statusBarItem) {
      this.statusBarItem.destroy();
    }
    if (this.dockerManager) {
      await this.dockerManager.stop();
    }
  }
  /**
   * 异步启动容器（不阻塞 Obsidian 启动）
   */
  async startContainerAsync() {
    try {
      this.statusBarItem.setStatus("starting");
      await this.dockerManager.start();
      this.statusBarItem.setStatus("running");
      new import_obsidian4.Notice("MCP Server \u5DF2\u542F\u52A8");
    } catch (error) {
      this.statusBarItem.setStatus("error");
      new import_obsidian4.Notice("MCP Server \u542F\u52A8\u5931\u8D25\uFF0C\u70B9\u51FB\u72B6\u6001\u680F\u56FE\u6807\u67E5\u770B\u65E5\u5FD7\u6216\u624B\u52A8\u91CD\u8BD5");
      console.error("Failed to start MCP Server:", error);
    }
  }
  /**
   * 重启容器
   */
  async restartContainer() {
    try {
      new import_obsidian4.Notice("\u6B63\u5728\u91CD\u542F MCP Server...");
      this.statusBarItem.setStatus("starting");
      await this.dockerManager.restart();
      this.statusBarItem.setStatus("running");
      new import_obsidian4.Notice("MCP Server \u5DF2\u91CD\u542F");
    } catch (error) {
      this.statusBarItem.setStatus("error");
      new import_obsidian4.Notice("MCP Server \u91CD\u542F\u5931\u8D25");
      console.error("Failed to restart MCP Server:", error);
    }
  }
  /**
   * 停止容器
   */
  async stopContainer() {
    try {
      await this.dockerManager.stop();
      this.statusBarItem.setStatus("stopped");
      new import_obsidian4.Notice("MCP Server \u5DF2\u505C\u6B62");
    } catch (error) {
      new import_obsidian4.Notice("\u505C\u6B62 MCP Server \u5931\u8D25");
      console.error("Failed to stop MCP Server:", error);
    }
  }
  /**
   * 打开日志查看器
   */
  openLogModal() {
    if (!this.logModal) {
      this.logModal = new LogModal(this.app, this.dockerManager);
    }
    this.logModal.open();
  }
  /**
   * 加载设置
   */
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  /**
   * 保存设置
   */
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
